### PR TITLE
Remove sigma_rule_status.csv from Installation Helper Scripts

### LINKED ISSUE #3062: sigma_rule_status.csv removed but still present in installation helper script
**Describe the bug**
Due to #2913, the `curl -s $GITHUB_BASE_URL/data/sigma_rule_status.csv > timesketch/etc/timesketch/sigma_rule_status.csv` command 404's. Due to the way curl works, no warning is shown and instead `cat timesketch/etc/timesketch/sigma_rule_status.csv
404: Not Found⏎                                    ` is written.

**To Reproduce**
curl -s -O https://raw.githubusercontent.com/google/timesketch/master/contrib/deploy_timesketch.sh
bash deploy_timesketch.sh

**Expected behavior**
No longer download outdated file

### PR DESCRIPTION
**Pull request by Aevyz**
**IMPORTANT: All Pull Requests should be connected to an issue, if you don't
have an issue, please start by creating an issue and link it to the PR.**

Please provide enough information so that others can review your pull request:

+ Removes 404'ing files (sigma_rule_status.csv)
+ Removes duplicate curl (tags.yml)
+ Powershell and Bash Script

**Checks**

- [ ] All tests succeed.
- [ ] Unit tests added.
- [ ] e2e tests added.
- [ ] Documentation updated.

**Closing issues**

Closes #3062

### CODE REVIEW

File: contrib/deploy_timesketch.sh [hunk 1]
```diff
@@ -92,11 +92,8 @@ curl -s $GITHUB_BASE_URL/data/generic.mappings > timesketch/etc/timesketch/gener
 curl -s $GITHUB_BASE_URL/data/regex_features.yaml > timesketch/etc/timesketch/regex_features.yaml
 curl -s $GITHUB_BASE_URL/data/winevt_features.yaml > timesketch/etc/timesketch/winevt_features.yaml
 curl -s $GITHUB_BASE_URL/data/ontology.yaml > timesketch/etc/timesketch/ontology.yaml
-curl -s $GITHUB_BASE_URL/data/sigma_rule_status.csv > timesketch/etc/timesketch/sigma_rule_status.csv
-curl -s $GITHUB_BASE_URL/data/tags.yaml > timesketch/etc/timesketch/tags.yaml
```
Comment (jkppr) [inline contrib/deploy_timesketch.sh:96]: Why also remove the `tags.yaml` file?  IIRC this still exists and should be used by the Tagger Analyzer. (https://github.com/google/timesketch/blob/master/data/tags.yaml)

**Review by jkppr — COMMENTED** [review]
Thanks for catching this error and fixing the deployment scripts. Please address the comments below.

File: contrib/deploy_timesketch.sh (hunk 1 above)
Comment (jkppr) [reply contrib/deploy_timesketch.sh:96]: My fault, it says in the initial comment: Removing a duplicate.

**Review by jkppr — APPROVED** [review]
lgtm
