### PR TITLE
Fixed #1600 by adding mappings to deployment script.

### LINKED ISSUE #1600: plaso.mappings missing in default setup
**Describe the bug**
I installed timesketch via docker as indicated on the github (Installed 2021-02-08 12:43 UTC). I want to import a timeline with the upload feature in the web gui. After a few minutes, I am presented with an error message. 
```
2021-02-08 12:59:40,156 [INFO] (MainProcess) PID:31 <data_location> Determined data location: /usr/share/plaso
ERROR: No such Elasticsearch mappings file: data/timesketch.mappings.

usage: psort.py [-h] [--troubles] [-V] [--analysis PLUGIN_LIST]
                [--process_memory_limit SIZE]
                [--temporary_directory DIRECTORY] [--worker_memory_limit SIZE]
                [--worker_timeout MINUTES] [--logfile FILENAME] [-d] [-q] [-u]
                [--status_view TYPE] [--slice DATE_TIME]
                [--slice_size SLICE_SIZE] [--slicer] [--data PATH] [-a]
                [--language LANGUAGE] [--output_time_zone TIME_ZONE]
                [-o FORMAT] [-w OUTPUT_FILE] [--index_name NAME]
                [--flush_interval INTERVAL] [--raw_fields]
                [--additional_fields ADDITIONAL_FIELDS]
                [--elastic_mappings PATH] [--elastic_user USERNAME]
                [--elastic_password PASSWORD] [--use_ssl]
                [--ca_certificates_file_path PATH]
                [--elastic_url_prefix URL_PREFIX] [--server HOSTNAME]
                [--port PORT] [--timeline_identifier IDENTIFIER]
                [--profilers PROFILERS_LIST] [--profiling_directory DIRECTORY]
                [--profiling_sample_rate SAMPLE_RATE]
                [STORAGE_FILE] [FILTER]
```

logs/worker.log:
```
cat logs/worker.log
[2021-02-08 12:59:36,593] celery.worker.strategy/INFO Received task: timesketch.lib.tasks.run_plaso[2700d353-22b5-46e8-ba9a-8f97a1192890]
[2021-02-08 12:59:37,056] timesketch.tasks/INFO Index timeline [TargetMachine_timeline_focused] to index [64a10d4df80d495b9993a6da4af6c6cf] (source: plaso)
[2021-02-08 12:59:44,016] celery.app.trace/INFO Task timesketch.lib.tasks.run_plaso[2700d353-22b5-46e8-ba9a-8f97a1192890] succeeded in 7.422250066000288s: '2021-02-08 12:59:40,156 [INFO] (MainProcess) PID:31 <data_location> Determined data location: /usr/share/plaso
ERROR: No such Elasticsearch mappings file: data/timesketch.mappings.

usage: psort.py [-h] [--troubles] [-V] [--analysis PLUGIN_LIST]
                [--process_memory_limit SIZE]
                [--temporary_directory DIRECTORY] [--worker_memory_limit SIZE]
                [--worker_timeout MINUTES] [--logfile FILENAME] [-d] [-q] [-u]
                [--status_view TYPE] [--slice DATE_TIME]
                [--slice_size SLICE_SIZE] [--slicer] [--data PATH] [-a]
                [--language LANGUAGE] [--output_time_zone TIME_ZONE]
                [-o FORMAT] [-w OUTPUT_FILE] [--index_name NAME]
                [--flush_interval INTERVAL] [--raw_fields]
                [--additional_fields ADDITIONAL_FIELDS]
                [--elastic_mappings PATH] [--elastic_user USERNAME]
                [--elastic_password PASSWORD] [--use_ssl]
                [--ca_certificates_file_path PATH]
               ...'
```
**To Reproduce**
Upload plaso-file in new sketch. Wait for error. 

**Expected behavior**
I expected my timeline to import in timesketch and be usable (finished indexing)

**Screenshots**

**Desktop (please complete the following information):**
 - Ubuntu 20.04
 - Chrome 

**Additional context**
plaso file generated with - log2timeline version 20201228

**Possible fix**
Add `curl -s $GITHUB_BASE_URL/data/plaso.mappings > timesketch/etc/timesketch/plaso.mappings` to `contrib/deploy_timesketch.sh`

### PR DESCRIPTION
**Pull request by kiddinn**

### CODE REVIEW

File: contrib/deploy_timesketch.sh [hunk 1]
```diff
@@ -79,6 +79,7 @@ curl -s $GITHUB_BASE_URL/docker/release/config.env > timesketch/config.env
 # Fetch default Timesketch config files
 curl -s $GITHUB_BASE_URL/data/timesketch.conf > timesketch/etc/timesketch/timesketch.conf
 curl -s $GITHUB_BASE_URL/data/tags.yaml > timesketch/etc/timesketch/tags.yaml
+curl -s $GITHUB_BASE_URL/data/plaso.mappings > timesketch/etc/timesketch/plaso.mappings
```
Comment (joachimmetz) [inline contrib/deploy_timesketch.sh:82]: This file should be available in plaso-data check if you need to set data path correctly

**Review by berggren — APPROVED** [review]
Pending Joachims comment, otherwise LGTM

File: contrib/deploy_timesketch.sh (hunk 1 above)
Comment (kiddinn) [reply contrib/deploy_timesketch.sh:82]: this is another mapping, since we moved all TS specifics over to Timesketch. The plaso mapping file is used in the Timesketch output module, and the default ES module, but we are now generating the index in TS so that we can more easily control the mapping file there, since this is more of a TS issue than a plaso one, so yes this is a separate file

**Review by kiddinn — COMMENTED** [review]
.

File: contrib/deploy_timesketch.sh (hunk 1 above)
Comment (joachimmetz) [reply contrib/deploy_timesketch.sh:82]: @berggren I'll follow up with @kiddinn off thread, question is resolved for this PR
