### PR TITLE
Fix missing plaso_formatters

### LINKED ISSUE #2931: bug Error message: ERROR: Unable to determine path to custom formatter definitions: /etc/timesketch/plaso_formatters.yaml
Hi !

after a fresh install with docker I've this error when I put a plaso file with the Web UI

image

### PR DESCRIPTION
**Pull request by jkppr**
When following the official installation instructions on timesketch.org the import of timelines will fail since the `plaso_formatters.yaml` is in the wrong folder.

This PR does:
* fix the location of plaso_formatters.yaml
* Adding context link config there as well

closes #2931

### CODE REVIEW

File: contrib/deploy_timesketch.sh [hunk 1]
```diff
@@ -97,7 +97,8 @@ curl -s $GITHUB_BASE_URL/data/intelligence_tag_metadata.yaml > timesketch/etc/ti
 curl -s $GITHUB_BASE_URL/data/sigma_config.yaml > timesketch/etc/timesketch/sigma_config.yaml
 curl -s $GITHUB_BASE_URL/data/sigma_rule_status.csv > timesketch/etc/timesketch/sigma_rule_status.csv
 curl -s $GITHUB_BASE_URL/data/sigma/rules/lnx_susp_zmap.yml > timesketch/etc/timesketch/sigma/rules/lnx_susp_zmap.yml
-curl -s $GITHUB_BASE_URL/data/plaso_formatters.yaml > timesketch/etc/plaso_formatters.yaml
+curl -s $GITHUB_BASE_URL/data/plaso_formatters.yaml > timesketch/etc/timesketch/plaso_formatters.yaml
+curl -s $GITHUB_BASE_URL/data/context_links.yaml > timesketch/etc/timesketch/context_links.yam
```
Comment (tomchop) [inline contrib/deploy_timesketch.sh:101]:
```suggestion
curl -s $GITHUB_BASE_URL/data/context_links.yaml > timesketch/etc/timesketch/context_links.yaml
```

**Review by tomchop — CHANGES_REQUESTED** [review]

**Review by berggren — APPROVED** [review]
