### PR TITLE
Fix for #2738 - Analyzer not in AnalyzerList

### LINKED ISSUE #2738: Analyzer UI error
**Describe the bug**
With existing analyzers the new Analyzer UI might throw the following (non blocking) error:
```
TypeError: Cannot read properties of undefined (reading 'description')
    at o.updateAnalyzerResultsData (AnalyzerResults.vue:186:1)
    at o.<anonymous> (AnalyzerResults.vue:174:1)
    at h (runtime.js:64:40)
    at Generator.<anonymous> (runtime.js:299:22)
    at Generator.next (runtime.js:124:21)
    at a (asyncToGenerator.js:4:20)
    at s (asyncToGenerator.js:23:9)
    at x.mb (app_bundle.js:29:385)
    at p.ya (app_bundle.js:23:249)
    at app_bundle.js:63:342
    at x.gf (app_bundle.js:30:229)
    at p.Oh (app_bundle.js:24:302)
    at g (app_bundle.js:20:381)
```

TODO: Check if `description` exists before trying to assign it. [code here](https://github.com/google/timesketch/blob/master/timesketch/frontend-ng/src/components/LeftPanel/AnalyzerResults.vue#L186)

### PR DESCRIPTION
**Pull request by jkppr**
This PR introduces an attempt to fix #2738 in the frontend analyzer result list.

### CODE REVIEW

File: timesketch/frontend-ng/src/components/LeftPanel/AnalyzerResults.vue [hunk 1]
```diff
@@ -179,14 +179,28 @@ export default {
...
+                  is_multi: this.analyzerList[session.analyzer_name].is_multi,
+                  display_name: this.analyzerList[session.analyzer_name].display_name,
+                },
+              }
+            } else {
+              perAnalyzer[session.analyzer_name] = {
+                timelines: {},
+                analyzerInfo: {
+                  name: session.analyzer_name,
+                  description: 'Issue#2738 - No description available.',
```
Comment (berggren) [inline timesketch/frontend-ng/src/components/LeftPanel/AnalyzerResults.vue:199]: why do we want to advertize the issue number here? I opt to remove it.

**Review by berggren — APPROVED** [review]

**Review by berggren — CHANGES_REQUESTED** [review]
Leave out the issue# for the end user

**Review by berggren — APPROVED** [review]
